/**
 * @file array_parameter.c
 *
 * @brief $$ = createArrayParameter();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ArrayParameter* createArrayParameter(ExpressionFactor* expression_factor,
		ArrayParameter* array_parameter)
 *
 */
ArrayParameter* createArrayParameter(ExpressionFactor* expression_factor,
		ArrayParameter* array_parameter) {

#ifdef ENABLE_TRACE
    printf("parser: createArrayParameter\\n");
#endif /* ENABLE_DUMP */

    ArrayParameter* ptr = _alloc_ds(ArrayParameter);
    initAst(&ptr->ast, NULL, AST_ARRAY_PARAMETER);
    ptr->expression_factor = expression_factor;
    ptr->array_parameter = array_parameter;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ArrayParameter data structure.
 *
 */
AstResult pass1ArrayParameter(ArrayParameter* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ArrayParameter\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = pass1ExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = pass1ArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ArrayParameter data structure.
 *
 */
AstResult pass2ArrayParameter(ArrayParameter* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ArrayParameter\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = pass2ExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = pass2ArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ArrayParameter data structure.
 *
 */
AstResult pass3ArrayParameter(ArrayParameter* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ArrayParameter\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = pass3ExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = pass3ArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ArrayParameter data structure.
 *
 */
AstResult emitArrayParameter(ArrayParameter* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitArrayParameter\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = emitExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = emitArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ArrayParameter data structure.
 *
 */
AstResult destroyArrayParameter(ArrayParameter* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyArrayParameter\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = destroyExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = destroyArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ArrayParameter data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpArrayParameter(ArrayParameter* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression_factor != NULL) {
            AstResult res = dumpExpressionFactor(ptr->expression_factor);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_parameter != NULL) {
            AstResult res = dumpArrayParameter(ptr->array_parameter);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
