/**
 * @file array_initializer.c
 *
 * @brief $$ = createArrayInitializer();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ArrayInitializer* createArrayInitializer(ExpressionList* expression_list)
 *
 */
ArrayInitializer* createArrayInitializer(ExpressionList* expression_list) {

#ifdef ENABLE_TRACE
    printf("parser: createArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    ArrayInitializer* ptr = _alloc_ds(ArrayInitializer);
    initAst(&ptr->ast, NULL, AST_ARRAY_INITIALIZER);
    ptr->expression_list = expression_list;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ArrayInitializer data structure.
 *
 */
AstResult pass1ArrayInitializer(ArrayInitializer* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass1ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ArrayInitializer data structure.
 *
 */
AstResult pass2ArrayInitializer(ArrayInitializer* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass2ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ArrayInitializer data structure.
 *
 */
AstResult pass3ArrayInitializer(ArrayInitializer* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass3ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ArrayInitializer data structure.
 *
 */
AstResult emitArrayInitializer(ArrayInitializer* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = emitExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ArrayInitializer data structure.
 *
 */
AstResult destroyArrayInitializer(ArrayInitializer* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyArrayInitializer\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = destroyExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ArrayInitializer data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpArrayInitializer(ArrayInitializer* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = dumpExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
