/**
 * @file array_initializer.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _ARRAY_INITIALIZER_H_
#define _ARRAY_INITIALIZER_H_

#include "ast.h"

typedef enum {
    ARRAY_INITIALIZER_OK,
    ARRAY_INITIALIZER_ERROR,
} ArrayInitializerType;

struct _array_initializer_ {
    Ast ast;
    ArrayInitializerType type;
    ExpressionList* expression_list;
};

ArrayInitializer* createArrayInitializer(ExpressionList*);
AstResult pass1ArrayInitializer(ArrayInitializer*);
AstResult pass2ArrayInitializer(ArrayInitializer*);
AstResult pass3ArrayInitializer(ArrayInitializer*);
AstResult emitArrayInitializer(ArrayInitializer*);
AstResult destroyArrayInitializer(ArrayInitializer*);

#ifdef ENABLE_DUMP
AstResult dumpArrayInitializer(ArrayInitializer* ptr);
#endif

#endif
