/**
 * @file assignment.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _ASSIGNMENT_H_
#define _ASSIGNMENT_H_

#include "ast.h"

typedef enum {
    ASSIGNMENT_OK,
    ASSIGNMENT_ERROR,
} AssignmentType;

struct _assignment_ {
    Ast ast;
    AssignmentType type;
    CompoundName* compound_name;
    Initialzer* initialzer;
    ArrayReference* array_reference;
};

Assignment* createAssignment(CompoundName*, Initialzer*, ArrayReference*);
AstResult pass1Assignment(Assignment*);
AstResult pass2Assignment(Assignment*);
AstResult pass3Assignment(Assignment*);
AstResult emitAssignment(Assignment*);
AstResult destroyAssignment(Assignment*);

#ifdef ENABLE_DUMP
AstResult dumpAssignment(Assignment* ptr);
#endif

#endif
