/**
 * @file assignment.c
 *
 * @brief $$ = createAssignment();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief Assignment* createAssignment(CompoundName* compound_name,
		Initialzer* initialzer,
		ArrayReference* array_reference)
 *
 */
Assignment* createAssignment(CompoundName* compound_name,
		Initialzer* initialzer,
		ArrayReference* array_reference) {

#ifdef ENABLE_TRACE
    printf("parser: createAssignment\\n");
#endif /* ENABLE_DUMP */

    Assignment* ptr = _alloc_ds(Assignment);
    initAst(&ptr->ast, NULL, AST_ASSIGNMENT);
    ptr->compound_name = compound_name;
    ptr->initialzer = initialzer;
    ptr->array_reference = array_reference;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for Assignment data structure.
 *
 */
AstResult pass1Assignment(Assignment* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1Assignment\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass1CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = pass1Initialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = pass1ArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for Assignment data structure.
 *
 */
AstResult pass2Assignment(Assignment* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2Assignment\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass2CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = pass2Initialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = pass2ArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for Assignment data structure.
 *
 */
AstResult pass3Assignment(Assignment* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3Assignment\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass3CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = pass3Initialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = pass3ArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for Assignment data structure.
 *
 */
AstResult emitAssignment(Assignment* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitAssignment\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = emitCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = emitInitialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = emitArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a Assignment data structure.
 *
 */
AstResult destroyAssignment(Assignment* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyAssignment\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = destroyCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = destroyInitialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = destroyArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump Assignment data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpAssignment(Assignment* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = dumpCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->initialzer != NULL) {
            AstResult res = dumpInitialzer(ptr->initialzer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_reference != NULL) {
            AstResult res = dumpArrayReference(ptr->array_reference);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
