/**
 * @file ast_includes.h
 *
 * This is the group include for all of the AST modules.
 */
#ifndef _AST_INCLUDES_H_
#define _AST_INCLUDES_H_

#include "ast.h"
#include "ast_typedefs.h"

/*
 * Includes.
 */
#include "module.h"
#include "module_list.h"
#include "compound_name.h"
#include "scope_operator.h"
#include "type_definition.h"
#include "constant_expression.h"
#include "symbol_type.h"
#include "cast_specifier.h"
#include "compound_name_in_parens_rule.h"
#include "array_reference.h"
#include "expression_factor.h"
#include "expression.h"
#include "expression_list.h"
#include "expression_in_parens_rule.h"
#include "expression_list_in_parens.h"
#include "func_reference.h"
#include "namespace_definition.h"
#include "class_name_parent.h"
#include "class_name.h"
#include "class_definition.h"
#include "class_definition_list.h"
#include "empty_parens_rule.h"
#include "func_decl_parameter_list.h"
#include "constructor_decl.h"
#include "destructor_decl.h"
#include "symbol_declaration.h"
#include "struct_declaration.h"
#include "struct_body.h"
#include "method_declaration.h"
#include "parameter_def_list.h"
#include "parameter_decl_element.h"
#include "parameter_decl_list.h"
#include "array_initializer.h"
#include "dict_init_item.h"
#include "dict_init_element.h"
#include "dict_init_list.h"
#include "dict_initializer.h"
#include "initialzer.h"
#include "data_definition.h"
#include "func_def_parameter_list.h"
#include "func_body_statement_list.h"
#include "func_body.h"
#include "func_definition.h"
#include "break_statement.h"
#include "continue_statement.h"
#include "yield_statement.h"
#include "except_clause.h"
#include "except_clause_intermediate_list.h"
#include "except_clause_final.h"
#include "except_clause_list.h"
#include "try_statement.h"
#include "else_clause.h"
#include "else_clause_intermediate_list.h"
#include "else_clause_final.h"
#include "else_clause_list.h"
#include "if_clause.h"
#include "if_statement.h"
#include "for_statement.h"
#include "while_statement.h"
#include "case_clause.h"
#include "case_clause_intermediate_list.h"
#include "case_clause_list.h"
#include "switch_statement.h"
#include "do_statement.h"
#include "array_parameter.h"
#include "array_parameter_list.h"
#include "class_definition_item.h"
#include "module_item.h"
#include "trace_statement.h"
#include "return_statement.h"
#include "print_statement.h"
#include "exit_statement.h"
#include "raise_statement.h"
#include "type_statement.h"
#include "assignment.h"
#include "func_body_statement.h"

#endif /* _AST_INCLUDES_H_ */