/**
 * @file break_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _BREAK_STATEMENT_H_
#define _BREAK_STATEMENT_H_

#include "ast.h"

typedef enum {
    BREAK_STATEMENT_OK,
    BREAK_STATEMENT_ERROR,
} BreakStatementType;

struct _break_statement_ {
    Ast ast;
    BreakStatementType type;
};

BreakStatement* createBreakStatement();
AstResult pass1BreakStatement(BreakStatement*);
AstResult pass2BreakStatement(BreakStatement*);
AstResult pass3BreakStatement(BreakStatement*);
AstResult emitBreakStatement(BreakStatement*);
AstResult destroyBreakStatement(BreakStatement*);

#ifdef ENABLE_DUMP
AstResult dumpBreakStatement(BreakStatement* ptr);
#endif

#endif
