/**
 * @file case_clause_intermediate_list.c
 *
 * @brief $$ = createCaseClauseIntermediateList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief CaseClauseIntermediateList* createCaseClauseIntermediateList(CaseClause* case_clause,
		CaseClauseIntermediateList* case_clause_intermediate_list)
 *
 */
CaseClauseIntermediateList* createCaseClauseIntermediateList(CaseClause* case_clause,
		CaseClauseIntermediateList* case_clause_intermediate_list) {

#ifdef ENABLE_TRACE
    printf("parser: createCaseClauseIntermediateList\\n");
#endif /* ENABLE_DUMP */

    CaseClauseIntermediateList* ptr = _alloc_ds(CaseClauseIntermediateList);
    initAst(&ptr->ast, NULL, AST_CASE_CLAUSE_INTERMEDIATE_LIST);
    ptr->case_clause = case_clause;
    ptr->case_clause_intermediate_list = case_clause_intermediate_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1CaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = pass1CaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass1CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2CaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = pass2CaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass2CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3CaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = pass3CaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass3CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitCaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = emitCaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = emitCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyCaseClauseIntermediateList(CaseClauseIntermediateList* ptr)
 *
 */
AstResult destroyCaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = destroyCaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = destroyCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpCaseClauseIntermediateList(CaseClauseIntermediateList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->case_clause != NULL) {
            AstResult res = dumpCaseClause(ptr->case_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = dumpCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
