/**
 * @file case_clause_list.c
 *
 * @brief $$ = createCaseClauseList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief CaseClauseList* createCaseClauseList(CaseClauseIntermediateList* case_clause_intermediate_list,
		FuncBody* func_body)
 *
 */
CaseClauseList* createCaseClauseList(CaseClauseIntermediateList* case_clause_intermediate_list,
		FuncBody* func_body) {

#ifdef ENABLE_TRACE
    printf("parser: createCaseClauseList\\n");
#endif /* ENABLE_DUMP */

    CaseClauseList* ptr = _alloc_ds(CaseClauseList);
    initAst(&ptr->ast, NULL, AST_CASE_CLAUSE_LIST);
    ptr->case_clause_intermediate_list = case_clause_intermediate_list;
    ptr->func_body = func_body;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1CaseClauseList(CaseClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass1CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass1FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2CaseClauseList(CaseClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass2CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass2FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3CaseClauseList(CaseClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = pass3CaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass3FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitCaseClauseList(CaseClauseList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = emitCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = emitFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyCaseClauseList(CaseClauseList* ptr)
 *
 */
AstResult destroyCaseClauseList(CaseClauseList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = destroyCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = destroyFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpCaseClauseList(CaseClauseList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->case_clause_intermediate_list != NULL) {
            AstResult res = dumpCaseClauseIntermediateList(ptr->case_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = dumpFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
