/**
 * @file case_clause_intermediate_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CASE_CLAUSE_INTERMEDIATE_LIST_H_
#define _CASE_CLAUSE_INTERMEDIATE_LIST_H_

#include "ast.h"

typedef enum {
    CASE_CLAUSE_INTERMEDIATE_LIST_OK,
    CASE_CLAUSE_INTERMEDIATE_LIST_ERROR,
} CaseClauseIntermediateListType;

struct _case_clause_intermediate_list_ {
    Ast ast;
    CaseClauseIntermediateListType type;
    CaseClause* case_clause;
    CaseClauseIntermediateList* case_clause_intermediate_list;
};

CaseClauseIntermediateList* createCaseClauseIntermediateList(CaseClause*, CaseClauseIntermediateList*);
AstResult pass1CaseClauseIntermediateList(CaseClauseIntermediateList*);
AstResult pass2CaseClauseIntermediateList(CaseClauseIntermediateList*);
AstResult pass3CaseClauseIntermediateList(CaseClauseIntermediateList*);
AstResult emitCaseClauseIntermediateList(CaseClauseIntermediateList*);
AstResult destroyCaseClauseIntermediateList(CaseClauseIntermediateList*);

#ifdef ENABLE_DUMP
AstResult dumpCaseClauseIntermediateList(CaseClauseIntermediateList* ptr);
#endif

#endif
