/**
 * @file case_clause.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CASE_CLAUSE_H_
#define _CASE_CLAUSE_H_

#include "ast.h"

typedef enum {
    CASE_CLAUSE_OK,
    CASE_CLAUSE_ERROR,
} CaseClauseType;

struct _case_clause_ {
    Ast ast;
    CaseClauseType type;
    ConstantExpression* constant_expression;
    FuncBody* func_body;
};

CaseClause* createCaseClause(ConstantExpression*, FuncBody*);
AstResult pass1CaseClause(CaseClause*);
AstResult pass2CaseClause(CaseClause*);
AstResult pass3CaseClause(CaseClause*);
AstResult emitCaseClause(CaseClause*);
AstResult destroyCaseClause(CaseClause*);

#ifdef ENABLE_DUMP
AstResult dumpCaseClause(CaseClause* ptr);
#endif

#endif
