/**
 * @file cast_specifier.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CAST_SPECIFIER_H_
#define _CAST_SPECIFIER_H_

#include "ast.h"

typedef enum {
    CAST_SPECIFIER_OK,
    CAST_SPECIFIER_ERROR,
} CastSpecifierType;

struct _cast_specifier_ {
    Ast ast;
    CastSpecifierType type;
    TypeDefinition* type_definition;
};

CastSpecifier* createCastSpecifier(TypeDefinition*);
AstResult pass1CastSpecifier(CastSpecifier*);
AstResult pass2CastSpecifier(CastSpecifier*);
AstResult pass3CastSpecifier(CastSpecifier*);
AstResult emitCastSpecifier(CastSpecifier*);
AstResult destroyCastSpecifier(CastSpecifier*);

#ifdef ENABLE_DUMP
AstResult dumpCastSpecifier(CastSpecifier* ptr);
#endif

#endif
