/**
 * @file cast_specifier.c
 *
 * @brief $$ = createCastSpecifier();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief CastSpecifier* createCastSpecifier(TypeDefinition* type_definition)
 *
 */
CastSpecifier* createCastSpecifier(TypeDefinition* type_definition) {

#ifdef ENABLE_TRACE
    printf("parser: createCastSpecifier\\n");
#endif /* ENABLE_DUMP */

    CastSpecifier* ptr = _alloc_ds(CastSpecifier);
    initAst(&ptr->ast, NULL, AST_CAST_SPECIFIER);
    ptr->type_definition = type_definition;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1CastSpecifier(CastSpecifier* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass1TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2CastSpecifier(CastSpecifier* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass2TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3CastSpecifier(CastSpecifier* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass3TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitCastSpecifier(CastSpecifier* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = emitTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyCastSpecifier(CastSpecifier* ptr)
 *
 */
AstResult destroyCastSpecifier(CastSpecifier* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = destroyTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpCastSpecifier(CastSpecifier* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = dumpTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
