/**
 * @file class_definition.c
 *
 * @brief $$ = createClassDefinition();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ClassDefinition* createClassDefinition(ClassDefinitionList* class_definition_list,
		ClassName* class_name)
 *
 */
ClassDefinition* createClassDefinition(ClassDefinitionList* class_definition_list,
		ClassName* class_name) {

#ifdef ENABLE_TRACE
    printf("parser: createClassDefinition\\n");
#endif /* ENABLE_DUMP */

    ClassDefinition* ptr = _alloc_ds(ClassDefinition);
    initAst(&ptr->ast, NULL, AST_CLASS_DEFINITION);
    ptr->class_definition_list = class_definition_list;
    ptr->class_name = class_name;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ClassDefinition data structure.
 *
 */
AstResult pass1ClassDefinition(ClassDefinition* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ClassDefinition\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = pass1ClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = pass1ClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ClassDefinition data structure.
 *
 */
AstResult pass2ClassDefinition(ClassDefinition* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ClassDefinition\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = pass2ClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = pass2ClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ClassDefinition data structure.
 *
 */
AstResult pass3ClassDefinition(ClassDefinition* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ClassDefinition\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = pass3ClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = pass3ClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ClassDefinition data structure.
 *
 */
AstResult emitClassDefinition(ClassDefinition* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitClassDefinition\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = emitClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = emitClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ClassDefinition data structure.
 *
 */
AstResult destroyClassDefinition(ClassDefinition* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyClassDefinition\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = destroyClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = destroyClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ClassDefinition data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpClassDefinition(ClassDefinition* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->class_definition_list != NULL) {
            AstResult res = dumpClassDefinitionList(ptr->class_definition_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->class_name != NULL) {
            AstResult res = dumpClassName(ptr->class_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
