/**
 * @file class_definition_item.c
 *
 * @brief $$ = createClassDefinitionItem();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ClassDefinitionItem* createClassDefinitionItem(SymbolDeclaration* symbol_declaration,
		MethodDeclaration* method_declaration,
		StructDeclaration* struct_declaration,
		ScopeOperator* scope_operator,
		ConstructorDecl* constructor_decl,
		DestructorDecl* destructor_decl)
 *
 */
ClassDefinitionItem* createClassDefinitionItem(SymbolDeclaration* symbol_declaration,
		MethodDeclaration* method_declaration,
		StructDeclaration* struct_declaration,
		ScopeOperator* scope_operator,
		ConstructorDecl* constructor_decl,
		DestructorDecl* destructor_decl) {

#ifdef ENABLE_TRACE
    printf("parser: createClassDefinitionItem\\n");
#endif /* ENABLE_DUMP */

    ClassDefinitionItem* ptr = _alloc_ds(ClassDefinitionItem);
    initAst(&ptr->ast, NULL, AST_CLASS_DEFINITION_ITEM);
    ptr->symbol_declaration = symbol_declaration;
    ptr->method_declaration = method_declaration;
    ptr->struct_declaration = struct_declaration;
    ptr->scope_operator = scope_operator;
    ptr->constructor_decl = constructor_decl;
    ptr->destructor_decl = destructor_decl;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ClassDefinitionItem(ClassDefinitionItem* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass1SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = pass1MethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = pass1StructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = pass1ScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = pass1ConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = pass1DestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ClassDefinitionItem(ClassDefinitionItem* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass2SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = pass2MethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = pass2StructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = pass2ScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = pass2ConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = pass2DestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ClassDefinitionItem(ClassDefinitionItem* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass3SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = pass3MethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = pass3StructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = pass3ScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = pass3ConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = pass3DestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitClassDefinitionItem(ClassDefinitionItem* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = emitSymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = emitMethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = emitStructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = emitScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = emitConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = emitDestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyClassDefinitionItem(ClassDefinitionItem* ptr)
 *
 */
AstResult destroyClassDefinitionItem(ClassDefinitionItem* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = destroySymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = destroyMethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = destroyStructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = destroyScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = destroyConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = destroyDestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpClassDefinitionItem(ClassDefinitionItem* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = dumpSymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->method_declaration != NULL) {
            AstResult res = dumpMethodDeclaration(ptr->method_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_declaration != NULL) {
            AstResult res = dumpStructDeclaration(ptr->struct_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->scope_operator != NULL) {
            AstResult res = dumpScopeOperator(ptr->scope_operator);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->constructor_decl != NULL) {
            AstResult res = dumpConstructorDecl(ptr->constructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->destructor_decl != NULL) {
            AstResult res = dumpDestructorDecl(ptr->destructor_decl);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
