/**
 * @file class_definition_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CLASS_DEFINITION_LIST_H_
#define _CLASS_DEFINITION_LIST_H_

#include "ast.h"

typedef enum {
    CLASS_DEFINITION_LIST_OK,
    CLASS_DEFINITION_LIST_ERROR,
} ClassDefinitionListType;

struct _class_definition_list_ {
    Ast ast;
    ClassDefinitionListType type;
    ClassDefinitionItem* class_definition_item;
    ClassDefinitionList* class_definition_list;
};

ClassDefinitionList* createClassDefinitionList(ClassDefinitionItem*, ClassDefinitionList*);
AstResult pass1ClassDefinitionList(ClassDefinitionList*);
AstResult pass2ClassDefinitionList(ClassDefinitionList*);
AstResult pass3ClassDefinitionList(ClassDefinitionList*);
AstResult emitClassDefinitionList(ClassDefinitionList*);
AstResult destroyClassDefinitionList(ClassDefinitionList*);

#ifdef ENABLE_DUMP
AstResult dumpClassDefinitionList(ClassDefinitionList* ptr);
#endif

#endif
