/**
 * @file class_name.c
 *
 * @brief $$ = createClassName();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ClassName* createClassName(const char* symbol,
		ClassNameParent* class_name_parent)
 *
 */
ClassName* createClassName(const char* symbol,
		ClassNameParent* class_name_parent) {

#ifdef ENABLE_TRACE
    printf("parser: createClassName\\n");
#endif /* ENABLE_DUMP */

    ClassName* ptr = _alloc_ds(ClassName);
    initAst(&ptr->ast, NULL, AST_CLASS_NAME);
    ptr->symbol = symbol;
    ptr->class_name_parent = class_name_parent;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ClassName data structure.
 *
 */
AstResult pass1ClassName(ClassName* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ClassName\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = pass1ClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ClassName data structure.
 *
 */
AstResult pass2ClassName(ClassName* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ClassName\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = pass2ClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ClassName data structure.
 *
 */
AstResult pass3ClassName(ClassName* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ClassName\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = pass3ClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ClassName data structure.
 *
 */
AstResult emitClassName(ClassName* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitClassName\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = emitClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ClassName data structure.
 *
 */
AstResult destroyClassName(ClassName* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyClassName\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = destroyClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ClassName data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpClassName(ClassName* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->class_name_parent != NULL) {
            AstResult res = dumpClassNameParent(ptr->class_name_parent);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
