/**
 * @file class_name.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CLASS_NAME_H_
#define _CLASS_NAME_H_

#include "ast.h"

typedef enum {
    CLASS_NAME_OK,
    CLASS_NAME_ERROR,
} ClassNameType;

struct _class_name_ {
    Ast ast;
    ClassNameType type;
    const char* symbol;
    ClassNameParent* class_name_parent;
};

ClassName* createClassName(const char*, ClassNameParent*);
AstResult pass1ClassName(ClassName*);
AstResult pass2ClassName(ClassName*);
AstResult pass3ClassName(ClassName*);
AstResult emitClassName(ClassName*);
AstResult destroyClassName(ClassName*);

#ifdef ENABLE_DUMP
AstResult dumpClassName(ClassName* ptr);
#endif

#endif
