/**
 * @file compound_name.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _COMPOUND_NAME_H_
#define _COMPOUND_NAME_H_

#include "ast.h"

typedef enum {
    COMPOUND_NAME_OK,
    COMPOUND_NAME_ERROR,
} CompoundNameType;

struct _compound_name_ {
    Ast ast;
    CompoundNameType type;
    const char* symbol;
    CompoundName* compound_name;
};

CompoundName* createCompoundName(const char*, CompoundName*);
AstResult pass1CompoundName(CompoundName*);
AstResult pass2CompoundName(CompoundName*);
AstResult pass3CompoundName(CompoundName*);
AstResult emitCompoundName(CompoundName*);
AstResult destroyCompoundName(CompoundName*);

#ifdef ENABLE_DUMP
AstResult dumpCompoundName(CompoundName* ptr);
#endif

#endif
