/**
 * @file compound_name_in_parens_rule.c
 *
 * @brief $$ = createCompoundNameInParensRule();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief CompoundNameInParensRule* createCompoundNameInParensRule(CompoundName* compound_name)
 *
 */
CompoundNameInParensRule* createCompoundNameInParensRule(CompoundName* compound_name) {

#ifdef ENABLE_TRACE
    printf("parser: createCompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    CompoundNameInParensRule* ptr = _alloc_ds(CompoundNameInParensRule);
    initAst(&ptr->ast, NULL, AST_COMPOUND_NAME_IN_PARENS_RULE);
    ptr->compound_name = compound_name;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for CompoundNameInParensRule data structure.
 *
 */
AstResult pass1CompoundNameInParensRule(CompoundNameInParensRule* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1CompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass1CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for CompoundNameInParensRule data structure.
 *
 */
AstResult pass2CompoundNameInParensRule(CompoundNameInParensRule* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2CompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass2CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for CompoundNameInParensRule data structure.
 *
 */
AstResult pass3CompoundNameInParensRule(CompoundNameInParensRule* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3CompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass3CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for CompoundNameInParensRule data structure.
 *
 */
AstResult emitCompoundNameInParensRule(CompoundNameInParensRule* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitCompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = emitCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a CompoundNameInParensRule data structure.
 *
 */
AstResult destroyCompoundNameInParensRule(CompoundNameInParensRule* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyCompoundNameInParensRule\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = destroyCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump CompoundNameInParensRule data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpCompoundNameInParensRule(CompoundNameInParensRule* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = dumpCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
