/**
 * @file constant_expression.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CONSTANT_EXPRESSION_H_
#define _CONSTANT_EXPRESSION_H_

#include "ast.h"

typedef enum {
    CONSTANT_EXPRESSION_OK,
    CONSTANT_EXPRESSION_ERROR,
} ConstantExpressionType;

struct _constant_expression_ {
    Ast ast;
    ConstantExpressionType type;
    double num;
    const char* strg;
};

ConstantExpression* createConstantExpression(double, const char*);
AstResult pass1ConstantExpression(ConstantExpression*);
AstResult pass2ConstantExpression(ConstantExpression*);
AstResult pass3ConstantExpression(ConstantExpression*);
AstResult emitConstantExpression(ConstantExpression*);
AstResult destroyConstantExpression(ConstantExpression*);

#ifdef ENABLE_DUMP
AstResult dumpConstantExpression(ConstantExpression* ptr);
#endif

#endif
