/**
 * @file constructor_decl.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _CONSTRUCTOR_DECL_H_
#define _CONSTRUCTOR_DECL_H_

#include "ast.h"

typedef enum {
    CONSTRUCTOR_DECL_OK,
    CONSTRUCTOR_DECL_ERROR,
} ConstructorDeclType;

struct _constructor_decl_ {
    Ast ast;
    ConstructorDeclType type;
    FuncDeclParameterList* func_decl_parameter_list;
};

ConstructorDecl* createConstructorDecl(FuncDeclParameterList*);
AstResult pass1ConstructorDecl(ConstructorDecl*);
AstResult pass2ConstructorDecl(ConstructorDecl*);
AstResult pass3ConstructorDecl(ConstructorDecl*);
AstResult emitConstructorDecl(ConstructorDecl*);
AstResult destroyConstructorDecl(ConstructorDecl*);

#ifdef ENABLE_DUMP
AstResult dumpConstructorDecl(ConstructorDecl* ptr);
#endif

#endif
