/**
 * @file data_definition.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _DATA_DEFINITION_H_
#define _DATA_DEFINITION_H_

#include "ast.h"

typedef enum {
    DATA_DEFINITION_OK,
    DATA_DEFINITION_ERROR,
} DataDefinitionType;

struct _data_definition_ {
    Ast ast;
    DataDefinitionType type;
    SymbolDeclaration* symbol_declaration;
    Initialzer* initialzer;
};

DataDefinition* createDataDefinition(SymbolDeclaration*, Initialzer*);
AstResult pass1DataDefinition(DataDefinition*);
AstResult pass2DataDefinition(DataDefinition*);
AstResult pass3DataDefinition(DataDefinition*);
AstResult emitDataDefinition(DataDefinition*);
AstResult destroyDataDefinition(DataDefinition*);

#ifdef ENABLE_DUMP
AstResult dumpDataDefinition(DataDefinition* ptr);
#endif

#endif
