/**
 * @file destructor_decl.c
 *
 * @brief $$ = createDestructorDecl();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief DestructorDecl* createDestructorDecl()
 *
 */
DestructorDecl* createDestructorDecl() {

#ifdef ENABLE_TRACE
    printf("parser: createDestructorDecl\\n");
#endif /* ENABLE_DUMP */

    DestructorDecl* ptr = _alloc_ds(DestructorDecl);
    initAst(&ptr->ast, NULL, AST_DESTRUCTOR_DECL);


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for DestructorDecl data structure.
 *
 */
AstResult pass1DestructorDecl(DestructorDecl* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1DestructorDecl\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items// nothing to traverse
    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for DestructorDecl data structure.
 *
 */
AstResult pass2DestructorDecl(DestructorDecl* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2DestructorDecl\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items// nothing to traverse
    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for DestructorDecl data structure.
 *
 */
AstResult pass3DestructorDecl(DestructorDecl* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3DestructorDecl\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items// nothing to traverse
    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for DestructorDecl data structure.
 *
 */
AstResult emitDestructorDecl(DestructorDecl* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitDestructorDecl\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items// nothing to traverse
    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a DestructorDecl data structure.
 *
 */
AstResult destroyDestructorDecl(DestructorDecl* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyDestructorDecl\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items// nothing to traverse
        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump DestructorDecl data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpDestructorDecl(DestructorDecl* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items// nothing to traverse
    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
