/**
 * @file dict_init_item.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _DICT_INIT_ITEM_H_
#define _DICT_INIT_ITEM_H_

#include "ast.h"

typedef enum {
    DICT_INIT_ITEM_OK,
    DICT_INIT_ITEM_ERROR,
} DictInitItemType;

struct _dict_init_item_ {
    Ast ast;
    DictInitItemType type;
    Expression* expression;
    DictInitializer* dict_initializer;
    ArrayInitializer* array_initializer;
};

DictInitItem* createDictInitItem(Expression*, DictInitializer*, ArrayInitializer*);
AstResult pass1DictInitItem(DictInitItem*);
AstResult pass2DictInitItem(DictInitItem*);
AstResult pass3DictInitItem(DictInitItem*);
AstResult emitDictInitItem(DictInitItem*);
AstResult destroyDictInitItem(DictInitItem*);

#ifdef ENABLE_DUMP
AstResult dumpDictInitItem(DictInitItem* ptr);
#endif

#endif
