/**
 * @file dict_init_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _DICT_INIT_LIST_H_
#define _DICT_INIT_LIST_H_

#include "ast.h"

typedef enum {
    DICT_INIT_LIST_OK,
    DICT_INIT_LIST_ERROR,
} DictInitListType;

struct _dict_init_list_ {
    Ast ast;
    DictInitListType type;
    DictInitElement* dict_init_element;
    DictInitList* dict_init_list;
};

DictInitList* createDictInitList(DictInitElement*, DictInitList*);
AstResult pass1DictInitList(DictInitList*);
AstResult pass2DictInitList(DictInitList*);
AstResult pass3DictInitList(DictInitList*);
AstResult emitDictInitList(DictInitList*);
AstResult destroyDictInitList(DictInitList*);

#ifdef ENABLE_DUMP
AstResult dumpDictInitList(DictInitList* ptr);
#endif

#endif
