/**
 * @file dict_init_item.c
 *
 * @brief $$ = createDictInitItem();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief DictInitItem* createDictInitItem(Expression* expression,
		DictInitializer* dict_initializer,
		ArrayInitializer* array_initializer)
 *
 */
DictInitItem* createDictInitItem(Expression* expression,
		DictInitializer* dict_initializer,
		ArrayInitializer* array_initializer) {

#ifdef ENABLE_TRACE
    printf("parser: createDictInitItem\\n");
#endif /* ENABLE_DUMP */

    DictInitItem* ptr = _alloc_ds(DictInitItem);
    initAst(&ptr->ast, NULL, AST_DICT_INIT_ITEM);
    ptr->expression = expression;
    ptr->dict_initializer = dict_initializer;
    ptr->array_initializer = array_initializer;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for DictInitItem data structure.
 *
 */
AstResult pass1DictInitItem(DictInitItem* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1DictInitItem\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass1Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = pass1DictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = pass1ArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for DictInitItem data structure.
 *
 */
AstResult pass2DictInitItem(DictInitItem* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2DictInitItem\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass2Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = pass2DictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = pass2ArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for DictInitItem data structure.
 *
 */
AstResult pass3DictInitItem(DictInitItem* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3DictInitItem\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass3Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = pass3DictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = pass3ArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for DictInitItem data structure.
 *
 */
AstResult emitDictInitItem(DictInitItem* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitDictInitItem\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = emitExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = emitDictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = emitArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a DictInitItem data structure.
 *
 */
AstResult destroyDictInitItem(DictInitItem* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyDictInitItem\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = destroyExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = destroyDictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = destroyArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump DictInitItem data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpDictInitItem(DictInitItem* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = dumpExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->dict_initializer != NULL) {
            AstResult res = dumpDictInitializer(ptr->dict_initializer);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->array_initializer != NULL) {
            AstResult res = dumpArrayInitializer(ptr->array_initializer);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
