/**
 * @file do_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _DO_STATEMENT_H_
#define _DO_STATEMENT_H_

#include "ast.h"

typedef enum {
    DO_STATEMENT_OK,
    DO_STATEMENT_ERROR,
} DoStatementType;

struct _do_statement_ {
    Ast ast;
    DoStatementType type;
    FuncBody* func_body;
    ExpressionInParensRule* expression_in_parens_rule;
};

DoStatement* createDoStatement(FuncBody*, ExpressionInParensRule*);
AstResult pass1DoStatement(DoStatement*);
AstResult pass2DoStatement(DoStatement*);
AstResult pass3DoStatement(DoStatement*);
AstResult emitDoStatement(DoStatement*);
AstResult destroyDoStatement(DoStatement*);

#ifdef ENABLE_DUMP
AstResult dumpDoStatement(DoStatement* ptr);
#endif

#endif
