/**
 * @file do_statement.c
 *
 * @brief $$ = createDoStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief DoStatement* createDoStatement(FuncBody* func_body,
		ExpressionInParensRule* expression_in_parens_rule)
 *
 */
DoStatement* createDoStatement(FuncBody* func_body,
		ExpressionInParensRule* expression_in_parens_rule) {

#ifdef ENABLE_TRACE
    printf("parser: createDoStatement\\n");
#endif /* ENABLE_DUMP */

    DoStatement* ptr = _alloc_ds(DoStatement);
    initAst(&ptr->ast, NULL, AST_DO_STATEMENT);
    ptr->func_body = func_body;
    ptr->expression_in_parens_rule = expression_in_parens_rule;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for DoStatement data structure.
 *
 */
AstResult pass1DoStatement(DoStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1DoStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = pass1FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass1ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for DoStatement data structure.
 *
 */
AstResult pass2DoStatement(DoStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2DoStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = pass2FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass2ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for DoStatement data structure.
 *
 */
AstResult pass3DoStatement(DoStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3DoStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = pass3FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass3ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for DoStatement data structure.
 *
 */
AstResult emitDoStatement(DoStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitDoStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = emitFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = emitExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a DoStatement data structure.
 *
 */
AstResult destroyDoStatement(DoStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyDoStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = destroyFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = destroyExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump DoStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpDoStatement(DoStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->func_body != NULL) {
            AstResult res = dumpFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = dumpExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
