/**
 * @file else_clause.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _ELSE_CLAUSE_H_
#define _ELSE_CLAUSE_H_

#include "ast.h"

typedef enum {
    ELSE_CLAUSE_OK,
    ELSE_CLAUSE_ERROR,
} ElseClauseType;

struct _else_clause_ {
    Ast ast;
    ElseClauseType type;
    Expression* expression;
    FuncBody* func_body;
};

ElseClause* createElseClause(Expression*, FuncBody*);
AstResult pass1ElseClause(ElseClause*);
AstResult pass2ElseClause(ElseClause*);
AstResult pass3ElseClause(ElseClause*);
AstResult emitElseClause(ElseClause*);
AstResult destroyElseClause(ElseClause*);

#ifdef ENABLE_DUMP
AstResult dumpElseClause(ElseClause* ptr);
#endif

#endif
