/**
 * @file else_clause_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _ELSE_CLAUSE_LIST_H_
#define _ELSE_CLAUSE_LIST_H_

#include "ast.h"

typedef enum {
    ELSE_CLAUSE_LIST_OK,
    ELSE_CLAUSE_LIST_ERROR,
} ElseClauseListType;

struct _else_clause_list_ {
    Ast ast;
    ElseClauseListType type;
    ElseClauseIntermediateList* else_clause_intermediate_list;
    ElseClauseFinal* else_clause_final;
};

ElseClauseList* createElseClauseList(ElseClauseIntermediateList*, ElseClauseFinal*);
AstResult pass1ElseClauseList(ElseClauseList*);
AstResult pass2ElseClauseList(ElseClauseList*);
AstResult pass3ElseClauseList(ElseClauseList*);
AstResult emitElseClauseList(ElseClauseList*);
AstResult destroyElseClauseList(ElseClauseList*);

#ifdef ENABLE_DUMP
AstResult dumpElseClauseList(ElseClauseList* ptr);
#endif

#endif
