/**
 * @file else_clause_final.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _ELSE_CLAUSE_FINAL_H_
#define _ELSE_CLAUSE_FINAL_H_

#include "ast.h"

typedef enum {
    ELSE_CLAUSE_FINAL_OK,
    ELSE_CLAUSE_FINAL_ERROR,
} ElseClauseFinalType;

struct _else_clause_final_ {
    Ast ast;
    ElseClauseFinalType type;
    EmptyParensRule* empty_parens_rule;
    FuncBody* func_body;
};

ElseClauseFinal* createElseClauseFinal(EmptyParensRule*, FuncBody*);
AstResult pass1ElseClauseFinal(ElseClauseFinal*);
AstResult pass2ElseClauseFinal(ElseClauseFinal*);
AstResult pass3ElseClauseFinal(ElseClauseFinal*);
AstResult emitElseClauseFinal(ElseClauseFinal*);
AstResult destroyElseClauseFinal(ElseClauseFinal*);

#ifdef ENABLE_DUMP
AstResult dumpElseClauseFinal(ElseClauseFinal* ptr);
#endif

#endif
