/**
 * @file empty_parens_rule.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EMPTY_PARENS_RULE_H_
#define _EMPTY_PARENS_RULE_H_

#include "ast.h"

typedef enum {
    EMPTY_PARENS_RULE_OK,
    EMPTY_PARENS_RULE_ERROR,
} EmptyParensRuleType;

struct _empty_parens_rule_ {
    Ast ast;
    EmptyParensRuleType type;
};

EmptyParensRule* createEmptyParensRule();
AstResult pass1EmptyParensRule(EmptyParensRule*);
AstResult pass2EmptyParensRule(EmptyParensRule*);
AstResult pass3EmptyParensRule(EmptyParensRule*);
AstResult emitEmptyParensRule(EmptyParensRule*);
AstResult destroyEmptyParensRule(EmptyParensRule*);

#ifdef ENABLE_DUMP
AstResult dumpEmptyParensRule(EmptyParensRule* ptr);
#endif

#endif
