/**
 * @file except_clause_intermediate_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXCEPT_CLAUSE_INTERMEDIATE_LIST_H_
#define _EXCEPT_CLAUSE_INTERMEDIATE_LIST_H_

#include "ast.h"

typedef enum {
    EXCEPT_CLAUSE_INTERMEDIATE_LIST_OK,
    EXCEPT_CLAUSE_INTERMEDIATE_LIST_ERROR,
} ExceptClauseIntermediateListType;

struct _except_clause_intermediate_list_ {
    Ast ast;
    ExceptClauseIntermediateListType type;
    ExceptClause* except_clause;
    ExceptClauseIntermediateList* except_clause_intermediate_list;
};

ExceptClauseIntermediateList* createExceptClauseIntermediateList(ExceptClause*, ExceptClauseIntermediateList*);
AstResult pass1ExceptClauseIntermediateList(ExceptClauseIntermediateList*);
AstResult pass2ExceptClauseIntermediateList(ExceptClauseIntermediateList*);
AstResult pass3ExceptClauseIntermediateList(ExceptClauseIntermediateList*);
AstResult emitExceptClauseIntermediateList(ExceptClauseIntermediateList*);
AstResult destroyExceptClauseIntermediateList(ExceptClauseIntermediateList*);

#ifdef ENABLE_DUMP
AstResult dumpExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr);
#endif

#endif
