/**
 * @file except_clause_list.c
 *
 * @brief $$ = createExceptClauseList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExceptClauseList* createExceptClauseList(ExceptClauseIntermediateList* except_clause_intermediate_list,
		ExceptClauseFinal* except_clause_final)
 *
 */
ExceptClauseList* createExceptClauseList(ExceptClauseIntermediateList* except_clause_intermediate_list,
		ExceptClauseFinal* except_clause_final) {

#ifdef ENABLE_TRACE
    printf("parser: createExceptClauseList\\n");
#endif /* ENABLE_DUMP */

    ExceptClauseList* ptr = _alloc_ds(ExceptClauseList);
    initAst(&ptr->ast, NULL, AST_EXCEPT_CLAUSE_LIST);
    ptr->except_clause_intermediate_list = except_clause_intermediate_list;
    ptr->except_clause_final = except_clause_final;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ExceptClauseList(ExceptClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass1ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = pass1ExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ExceptClauseList(ExceptClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass2ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = pass2ExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ExceptClauseList(ExceptClauseList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass3ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = pass3ExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitExceptClauseList(ExceptClauseList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = emitExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = emitExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyExceptClauseList(ExceptClauseList* ptr)
 *
 */
AstResult destroyExceptClauseList(ExceptClauseList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = destroyExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = destroyExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExceptClauseList(ExceptClauseList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = dumpExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_final != NULL) {
            AstResult res = dumpExceptClauseFinal(ptr->except_clause_final);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
