/**
 * @file except_clause_intermediate_list.c
 *
 * @brief $$ = createExceptClauseIntermediateList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExceptClauseIntermediateList* createExceptClauseIntermediateList(ExceptClause* except_clause,
		ExceptClauseIntermediateList* except_clause_intermediate_list)
 *
 */
ExceptClauseIntermediateList* createExceptClauseIntermediateList(ExceptClause* except_clause,
		ExceptClauseIntermediateList* except_clause_intermediate_list) {

#ifdef ENABLE_TRACE
    printf("parser: createExceptClauseIntermediateList\\n");
#endif /* ENABLE_DUMP */

    ExceptClauseIntermediateList* ptr = _alloc_ds(ExceptClauseIntermediateList);
    initAst(&ptr->ast, NULL, AST_EXCEPT_CLAUSE_INTERMEDIATE_LIST);
    ptr->except_clause = except_clause;
    ptr->except_clause_intermediate_list = except_clause_intermediate_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = pass1ExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass1ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = pass2ExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass2ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = pass3ExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = pass3ExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = emitExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = emitExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr)
 *
 */
AstResult destroyExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = destroyExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = destroyExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExceptClauseIntermediateList(ExceptClauseIntermediateList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->except_clause != NULL) {
            AstResult res = dumpExceptClause(ptr->except_clause);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_intermediate_list != NULL) {
            AstResult res = dumpExceptClauseIntermediateList(ptr->except_clause_intermediate_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
