/**
 * @file except_clause.c
 *
 * @brief $$ = createExceptClause();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExceptClause* createExceptClause(CompoundNameInParensRule* compound_name_in_parens_rule,
		FuncBody* func_body)
 *
 */
ExceptClause* createExceptClause(CompoundNameInParensRule* compound_name_in_parens_rule,
		FuncBody* func_body) {

#ifdef ENABLE_TRACE
    printf("parser: createExceptClause\\n");
#endif /* ENABLE_DUMP */

    ExceptClause* ptr = _alloc_ds(ExceptClause);
    initAst(&ptr->ast, NULL, AST_EXCEPT_CLAUSE);
    ptr->compound_name_in_parens_rule = compound_name_in_parens_rule;
    ptr->func_body = func_body;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ExceptClause(ExceptClause* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass1CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass1FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ExceptClause(ExceptClause* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass2CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass2FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ExceptClause(ExceptClause* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass3CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass3FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitExceptClause(ExceptClause* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = emitCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = emitFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyExceptClause(ExceptClause* ptr)
 *
 */
AstResult destroyExceptClause(ExceptClause* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = destroyCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = destroyFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExceptClause(ExceptClause* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = dumpCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = dumpFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
