/**
 * @file except_clause_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXCEPT_CLAUSE_LIST_H_
#define _EXCEPT_CLAUSE_LIST_H_

#include "ast.h"

typedef enum {
    EXCEPT_CLAUSE_LIST_OK,
    EXCEPT_CLAUSE_LIST_ERROR,
} ExceptClauseListType;

struct _except_clause_list_ {
    Ast ast;
    ExceptClauseListType type;
    ExceptClauseIntermediateList* except_clause_intermediate_list;
    ExceptClauseFinal* except_clause_final;
};

ExceptClauseList* createExceptClauseList(ExceptClauseIntermediateList*, ExceptClauseFinal*);
AstResult pass1ExceptClauseList(ExceptClauseList*);
AstResult pass2ExceptClauseList(ExceptClauseList*);
AstResult pass3ExceptClauseList(ExceptClauseList*);
AstResult emitExceptClauseList(ExceptClauseList*);
AstResult destroyExceptClauseList(ExceptClauseList*);

#ifdef ENABLE_DUMP
AstResult dumpExceptClauseList(ExceptClauseList* ptr);
#endif

#endif
