/**
 * @file exit_statement.c
 *
 * @brief $$ = createExitStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExitStatement* createExitStatement(Expression* expression)
 *
 */
ExitStatement* createExitStatement(Expression* expression) {

#ifdef ENABLE_TRACE
    printf("parser: createExitStatement\\n");
#endif /* ENABLE_DUMP */

    ExitStatement* ptr = _alloc_ds(ExitStatement);
    initAst(&ptr->ast, NULL, AST_EXIT_STATEMENT);
    ptr->expression = expression;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ExitStatement data structure.
 *
 */
AstResult pass1ExitStatement(ExitStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ExitStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass1Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ExitStatement data structure.
 *
 */
AstResult pass2ExitStatement(ExitStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ExitStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass2Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ExitStatement data structure.
 *
 */
AstResult pass3ExitStatement(ExitStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ExitStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass3Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ExitStatement data structure.
 *
 */
AstResult emitExitStatement(ExitStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitExitStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = emitExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ExitStatement data structure.
 *
 */
AstResult destroyExitStatement(ExitStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyExitStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = destroyExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ExitStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExitStatement(ExitStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = dumpExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
