/**
 * @file exit_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXIT_STATEMENT_H_
#define _EXIT_STATEMENT_H_

#include "ast.h"

typedef enum {
    EXIT_STATEMENT_OK,
    EXIT_STATEMENT_ERROR,
} ExitStatementType;

struct _exit_statement_ {
    Ast ast;
    ExitStatementType type;
    Expression* expression;
};

ExitStatement* createExitStatement(Expression*);
AstResult pass1ExitStatement(ExitStatement*);
AstResult pass2ExitStatement(ExitStatement*);
AstResult pass3ExitStatement(ExitStatement*);
AstResult emitExitStatement(ExitStatement*);
AstResult destroyExitStatement(ExitStatement*);

#ifdef ENABLE_DUMP
AstResult dumpExitStatement(ExitStatement* ptr);
#endif

#endif
