/**
 * @file expression_in_parens_rule.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXPRESSION_IN_PARENS_RULE_H_
#define _EXPRESSION_IN_PARENS_RULE_H_

#include "ast.h"

typedef enum {
    EXPRESSION_IN_PARENS_RULE_OK,
    EXPRESSION_IN_PARENS_RULE_ERROR,
} ExpressionInParensRuleType;

struct _expression_in_parens_rule_ {
    Ast ast;
    ExpressionInParensRuleType type;
    Expression* expression;
    EmptyParensRule* empty_parens_rule;
};

ExpressionInParensRule* createExpressionInParensRule(Expression*, EmptyParensRule*);
AstResult pass1ExpressionInParensRule(ExpressionInParensRule*);
AstResult pass2ExpressionInParensRule(ExpressionInParensRule*);
AstResult pass3ExpressionInParensRule(ExpressionInParensRule*);
AstResult emitExpressionInParensRule(ExpressionInParensRule*);
AstResult destroyExpressionInParensRule(ExpressionInParensRule*);

#ifdef ENABLE_DUMP
AstResult dumpExpressionInParensRule(ExpressionInParensRule* ptr);
#endif

#endif
