/**
 * @file expression_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXPRESSION_LIST_H_
#define _EXPRESSION_LIST_H_

#include "ast.h"

typedef enum {
    EXPRESSION_LIST_OK,
    EXPRESSION_LIST_ERROR,
} ExpressionListType;

struct _expression_list_ {
    Ast ast;
    ExpressionListType type;
    Expression* expression;
    ExpressionList* expression_list;
};

ExpressionList* createExpressionList(Expression*, ExpressionList*);
AstResult pass1ExpressionList(ExpressionList*);
AstResult pass2ExpressionList(ExpressionList*);
AstResult pass3ExpressionList(ExpressionList*);
AstResult emitExpressionList(ExpressionList*);
AstResult destroyExpressionList(ExpressionList*);

#ifdef ENABLE_DUMP
AstResult dumpExpressionList(ExpressionList* ptr);
#endif

#endif
