/**
 * @file expression_list.c
 *
 * @brief $$ = createExpressionList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExpressionList* createExpressionList(Expression* expression,
		ExpressionList* expression_list)
 *
 */
ExpressionList* createExpressionList(Expression* expression,
		ExpressionList* expression_list) {

#ifdef ENABLE_TRACE
    printf("parser: createExpressionList\\n");
#endif /* ENABLE_DUMP */

    ExpressionList* ptr = _alloc_ds(ExpressionList);
    initAst(&ptr->ast, NULL, AST_EXPRESSION_LIST);
    ptr->expression = expression;
    ptr->expression_list = expression_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ExpressionList(ExpressionList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass1Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = pass1ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ExpressionList(ExpressionList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass2Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = pass2ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ExpressionList(ExpressionList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass3Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = pass3ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitExpressionList(ExpressionList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = emitExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = emitExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyExpressionList(ExpressionList* ptr)
 *
 */
AstResult destroyExpressionList(ExpressionList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = destroyExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = destroyExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExpressionList(ExpressionList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = dumpExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list != NULL) {
            AstResult res = dumpExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
