/**
 * @file expression.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXPRESSION_H_
#define _EXPRESSION_H_

#include "ast.h"

typedef enum {
    EXPRESSION_OK,
    EXPRESSION_ERROR,
} ExpressionType;

struct _expression_ {
    Ast ast;
    ExpressionType type;
    ExpressionFactor* expression_factor;
    Expression* expression;
    CastSpecifier* cast_specifier;
    ExpressionInParensRule* expression_in_parens_rule;
};

Expression* createExpression(ExpressionFactor*, Expression*, CastSpecifier*, ExpressionInParensRule*);
AstResult pass1Expression(Expression*);
AstResult pass2Expression(Expression*);
AstResult pass3Expression(Expression*);
AstResult emitExpression(Expression*);
AstResult destroyExpression(Expression*);

#ifdef ENABLE_DUMP
AstResult dumpExpression(Expression* ptr);
#endif

#endif
