/**
 * @file expression_list_in_parens.c
 *
 * @brief $$ = createExpressionListInParens();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ExpressionListInParens* createExpressionListInParens(ExpressionList* expression_list,
		EmptyParensRule* empty_parens_rule)
 *
 */
ExpressionListInParens* createExpressionListInParens(ExpressionList* expression_list,
		EmptyParensRule* empty_parens_rule) {

#ifdef ENABLE_TRACE
    printf("parser: createExpressionListInParens\\n");
#endif /* ENABLE_DUMP */

    ExpressionListInParens* ptr = _alloc_ds(ExpressionListInParens);
    initAst(&ptr->ast, NULL, AST_EXPRESSION_LIST_IN_PARENS);
    ptr->expression_list = expression_list;
    ptr->empty_parens_rule = empty_parens_rule;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1ExpressionListInParens(ExpressionListInParens* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass1ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass1EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2ExpressionListInParens(ExpressionListInParens* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass2ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass2EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3ExpressionListInParens(ExpressionListInParens* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = pass3ExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass3EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitExpressionListInParens(ExpressionListInParens* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = emitExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = emitEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyExpressionListInParens(ExpressionListInParens* ptr)
 *
 */
AstResult destroyExpressionListInParens(ExpressionListInParens* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = destroyExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = destroyEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpExpressionListInParens(ExpressionListInParens* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression_list != NULL) {
            AstResult res = dumpExpressionList(ptr->expression_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = dumpEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
