/**
 * @file expression_factor.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _EXPRESSION_FACTOR_H_
#define _EXPRESSION_FACTOR_H_

#include "ast.h"

typedef enum {
    EXPRESSION_FACTOR_OK,
    EXPRESSION_FACTOR_ERROR,
} ExpressionFactorType;

struct _expression_factor_ {
    Ast ast;
    ExpressionFactorType type;
    ConstantExpression* constant_expression;
    CompoundName* compound_name;
    ArrayReference* array_reference;
    FuncReference* func_reference;
};

ExpressionFactor* createExpressionFactor(ConstantExpression*, CompoundName*, ArrayReference*, FuncReference*);
AstResult pass1ExpressionFactor(ExpressionFactor*);
AstResult pass2ExpressionFactor(ExpressionFactor*);
AstResult pass3ExpressionFactor(ExpressionFactor*);
AstResult emitExpressionFactor(ExpressionFactor*);
AstResult destroyExpressionFactor(ExpressionFactor*);

#ifdef ENABLE_DUMP
AstResult dumpExpressionFactor(ExpressionFactor* ptr);
#endif

#endif
