/**
 * @file func_reference.c
 *
 * @brief $$ = createFuncReference();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief FuncReference* createFuncReference(CompoundName* compound_name,
		ExpressionListInParens* expression_list_in_parens)
 *
 */
FuncReference* createFuncReference(CompoundName* compound_name,
		ExpressionListInParens* expression_list_in_parens) {

#ifdef ENABLE_TRACE
    printf("parser: createFuncReference\\n");
#endif /* ENABLE_DUMP */

    FuncReference* ptr = _alloc_ds(FuncReference);
    initAst(&ptr->ast, NULL, AST_FUNC_REFERENCE);
    ptr->compound_name = compound_name;
    ptr->expression_list_in_parens = expression_list_in_parens;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1FuncReference(FuncReference* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass1CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = pass1ExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2FuncReference(FuncReference* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass2CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = pass2ExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3FuncReference(FuncReference* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = pass3CompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = pass3ExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitFuncReference(FuncReference* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = emitCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = emitExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyFuncReference(FuncReference* ptr)
 *
 */
AstResult destroyFuncReference(FuncReference* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = destroyCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = destroyExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpFuncReference(FuncReference* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->compound_name != NULL) {
            AstResult res = dumpCompoundName(ptr->compound_name);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->expression_list_in_parens != NULL) {
            AstResult res = dumpExpressionListInParens(ptr->expression_list_in_parens);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
