/**
 * @file func_body_statement_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _FUNC_BODY_STATEMENT_LIST_H_
#define _FUNC_BODY_STATEMENT_LIST_H_

#include "ast.h"

typedef enum {
    FUNC_BODY_STATEMENT_LIST_OK,
    FUNC_BODY_STATEMENT_LIST_ERROR,
} FuncBodyStatementListType;

struct _func_body_statement_list_ {
    Ast ast;
    FuncBodyStatementListType type;
    FuncBodyStatement* func_body_statement;
    FuncBodyStatementList* func_body_statement_list;
};

FuncBodyStatementList* createFuncBodyStatementList(FuncBodyStatement*, FuncBodyStatementList*);
AstResult pass1FuncBodyStatementList(FuncBodyStatementList*);
AstResult pass2FuncBodyStatementList(FuncBodyStatementList*);
AstResult pass3FuncBodyStatementList(FuncBodyStatementList*);
AstResult emitFuncBodyStatementList(FuncBodyStatementList*);
AstResult destroyFuncBodyStatementList(FuncBodyStatementList*);

#ifdef ENABLE_DUMP
AstResult dumpFuncBodyStatementList(FuncBodyStatementList* ptr);
#endif

#endif
