/**
 * @file func_body_statement_list.c
 *
 * @brief $$ = createFuncBodyStatementList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief FuncBodyStatementList* createFuncBodyStatementList(FuncBodyStatement* func_body_statement,
		FuncBodyStatementList* func_body_statement_list)
 *
 */
FuncBodyStatementList* createFuncBodyStatementList(FuncBodyStatement* func_body_statement,
		FuncBodyStatementList* func_body_statement_list) {

#ifdef ENABLE_TRACE
    printf("parser: createFuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    FuncBodyStatementList* ptr = _alloc_ds(FuncBodyStatementList);
    initAst(&ptr->ast, NULL, AST_FUNC_BODY_STATEMENT_LIST);
    ptr->func_body_statement = func_body_statement;
    ptr->func_body_statement_list = func_body_statement_list;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for FuncBodyStatementList data structure.
 *
 */
AstResult pass1FuncBodyStatementList(FuncBodyStatementList* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1FuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = pass1FuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass1FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for FuncBodyStatementList data structure.
 *
 */
AstResult pass2FuncBodyStatementList(FuncBodyStatementList* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2FuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = pass2FuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass2FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for FuncBodyStatementList data structure.
 *
 */
AstResult pass3FuncBodyStatementList(FuncBodyStatementList* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3FuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = pass3FuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass3FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for FuncBodyStatementList data structure.
 *
 */
AstResult emitFuncBodyStatementList(FuncBodyStatementList* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitFuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = emitFuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = emitFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a FuncBodyStatementList data structure.
 *
 */
AstResult destroyFuncBodyStatementList(FuncBodyStatementList* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyFuncBodyStatementList\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = destroyFuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = destroyFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump FuncBodyStatementList data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpFuncBodyStatementList(FuncBodyStatementList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->func_body_statement != NULL) {
            AstResult res = dumpFuncBodyStatement(ptr->func_body_statement);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body_statement_list != NULL) {
            AstResult res = dumpFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
