/**
 * @file func_decl_parameter_list.c
 *
 * @brief $$ = createFuncDeclParameterList();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief FuncDeclParameterList* createFuncDeclParameterList(ParameterDeclList* parameter_decl_list,
		EmptyParensRule* empty_parens_rule)
 *
 */
FuncDeclParameterList* createFuncDeclParameterList(ParameterDeclList* parameter_decl_list,
		EmptyParensRule* empty_parens_rule) {

#ifdef ENABLE_TRACE
    printf("parser: createFuncDeclParameterList\\n");
#endif /* ENABLE_DUMP */

    FuncDeclParameterList* ptr = _alloc_ds(FuncDeclParameterList);
    initAst(&ptr->ast, NULL, AST_FUNC_DECL_PARAMETER_LIST);
    ptr->parameter_decl_list = parameter_decl_list;
    ptr->empty_parens_rule = empty_parens_rule;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1FuncDeclParameterList(FuncDeclParameterList* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = pass1ParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass1EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2FuncDeclParameterList(FuncDeclParameterList* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = pass2ParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass2EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3FuncDeclParameterList(FuncDeclParameterList* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = pass3ParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = pass3EmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitFuncDeclParameterList(FuncDeclParameterList* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = emitParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = emitEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyFuncDeclParameterList(FuncDeclParameterList* ptr)
 *
 */
AstResult destroyFuncDeclParameterList(FuncDeclParameterList* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = destroyParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = destroyEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpFuncDeclParameterList(FuncDeclParameterList* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->parameter_decl_list != NULL) {
            AstResult res = dumpParameterDeclList(ptr->parameter_decl_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->empty_parens_rule != NULL) {
            AstResult res = dumpEmptyParensRule(ptr->empty_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
