/**
 * @file func_reference.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _FUNC_REFERENCE_H_
#define _FUNC_REFERENCE_H_

#include "ast.h"

typedef enum {
    FUNC_REFERENCE_OK,
    FUNC_REFERENCE_ERROR,
} FuncReferenceType;

struct _func_reference_ {
    Ast ast;
    FuncReferenceType type;
    CompoundName* compound_name;
    ExpressionListInParens* expression_list_in_parens;
};

FuncReference* createFuncReference(CompoundName*, ExpressionListInParens*);
AstResult pass1FuncReference(FuncReference*);
AstResult pass2FuncReference(FuncReference*);
AstResult pass3FuncReference(FuncReference*);
AstResult emitFuncReference(FuncReference*);
AstResult destroyFuncReference(FuncReference*);

#ifdef ENABLE_DUMP
AstResult dumpFuncReference(FuncReference* ptr);
#endif

#endif
