/**
 * @file func_body.c
 *
 * @brief $$ = createFuncBody();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief FuncBody* createFuncBody(FuncBodyStatementList* func_body_statement_list)
 *
 */
FuncBody* createFuncBody(FuncBodyStatementList* func_body_statement_list) {

#ifdef ENABLE_TRACE
    printf("parser: createFuncBody\\n");
#endif /* ENABLE_DUMP */

    FuncBody* ptr = _alloc_ds(FuncBody);
    initAst(&ptr->ast, NULL, AST_FUNC_BODY);
    ptr->func_body_statement_list = func_body_statement_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1FuncBody(FuncBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass1FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2FuncBody(FuncBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass2FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3FuncBody(FuncBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass3FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitFuncBody(FuncBody* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = emitFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyFuncBody(FuncBody* ptr)
 *
 */
AstResult destroyFuncBody(FuncBody* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = destroyFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpFuncBody(FuncBody* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = dumpFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
