/**
 * @file if_clause.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _IF_CLAUSE_H_
#define _IF_CLAUSE_H_

#include "ast.h"

typedef enum {
    IF_CLAUSE_OK,
    IF_CLAUSE_ERROR,
} IfClauseType;

struct _if_clause_ {
    Ast ast;
    IfClauseType type;
    ExpressionInParensRule* expression_in_parens_rule;
    FuncBody* func_body;
};

IfClause* createIfClause(ExpressionInParensRule*, FuncBody*);
AstResult pass1IfClause(IfClause*);
AstResult pass2IfClause(IfClause*);
AstResult pass3IfClause(IfClause*);
AstResult emitIfClause(IfClause*);
AstResult destroyIfClause(IfClause*);

#ifdef ENABLE_DUMP
AstResult dumpIfClause(IfClause* ptr);
#endif

#endif
