/**
 * @file if_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _IF_STATEMENT_H_
#define _IF_STATEMENT_H_

#include "ast.h"

typedef enum {
    IF_STATEMENT_OK,
    IF_STATEMENT_ERROR,
} IfStatementType;

struct _if_statement_ {
    Ast ast;
    IfStatementType type;
    IfClause* if_clause;
    ElseClauseList* else_clause_list;
};

IfStatement* createIfStatement(IfClause*, ElseClauseList*);
AstResult pass1IfStatement(IfStatement*);
AstResult pass2IfStatement(IfStatement*);
AstResult pass3IfStatement(IfStatement*);
AstResult emitIfStatement(IfStatement*);
AstResult destroyIfStatement(IfStatement*);

#ifdef ENABLE_DUMP
AstResult dumpIfStatement(IfStatement* ptr);
#endif

#endif
