/**
 * @file initialzer.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _INITIALZER_H_
#define _INITIALZER_H_

#include "ast.h"

typedef enum {
    INITIALZER_OK,
    INITIALZER_ERROR,
} InitialzerType;

struct _initialzer_ {
    Ast ast;
    InitialzerType type;
    Expression* expression;
    ArrayInitializer* array_initializer;
    DictInitializer* dict_initializer;
    CastSpecifier* cast_specifier;
    Initialzer* initialzer;
};

Initialzer* createInitialzer(Expression*, ArrayInitializer*, DictInitializer*, CastSpecifier*, Initialzer*);
AstResult pass1Initialzer(Initialzer*);
AstResult pass2Initialzer(Initialzer*);
AstResult pass3Initialzer(Initialzer*);
AstResult emitInitialzer(Initialzer*);
AstResult destroyInitialzer(Initialzer*);

#ifdef ENABLE_DUMP
AstResult dumpInitialzer(Initialzer* ptr);
#endif

#endif
