/**
 * @file loop_body_statement_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _LOOP_BODY_STATEMENT_LIST_H_
#define _LOOP_BODY_STATEMENT_LIST_H_

#include "ast.h"

typedef enum {
    LOOP_BODY_STATEMENT_LIST_OK,
    LOOP_BODY_STATEMENT_LIST_ERROR,
} LoopBodyStatementListType;

struct _loop_body_statement_list_ {
    Ast ast;
    LoopBodyStatementListType type;
    LoopBodyStatement* loop_body_statement;
    LoopBodyStatementList* loop_body_statement_list;
};

LoopBodyStatementList* createLoopBodyStatementList(LoopBodyStatement*, LoopBodyStatementList*);
AstResult pass1LoopBodyStatementList(LoopBodyStatementList*);
AstResult pass2LoopBodyStatementList(LoopBodyStatementList*);
AstResult pass3LoopBodyStatementList(LoopBodyStatementList*);
AstResult emitLoopBodyStatementList(LoopBodyStatementList*);
AstResult destroyLoopBodyStatementList(LoopBodyStatementList*);

#ifdef ENABLE_DUMP
AstResult dumpLoopBodyStatementList(LoopBodyStatementList* ptr);
#endif

#endif
