/**
 * @file loop_body.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _LOOP_BODY_H_
#define _LOOP_BODY_H_

#include "ast.h"

typedef enum {
    LOOP_BODY_OK,
    LOOP_BODY_ERROR,
} LoopBodyType;

struct _loop_body_ {
    Ast ast;
    LoopBodyType type;
    LoopBodyStatementList* loop_body_statement_list;
};

LoopBody* createLoopBody(LoopBodyStatementList*);
AstResult pass1LoopBody(LoopBody*);
AstResult pass2LoopBody(LoopBody*);
AstResult pass3LoopBody(LoopBody*);
AstResult emitLoopBody(LoopBody*);
AstResult destroyLoopBody(LoopBody*);

#ifdef ENABLE_DUMP
AstResult dumpLoopBody(LoopBody* ptr);
#endif

#endif
