/**
 * @file loop_body.c
 *
 * @brief $$ = createLoopBody();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief LoopBody* createLoopBody(LoopBodyStatementList* loop_body_statement_list)
 *
 */
LoopBody* createLoopBody(LoopBodyStatementList* loop_body_statement_list) {

#ifdef ENABLE_TRACE
    printf("parser: createLoopBody\\n");
#endif /* ENABLE_DUMP */

    LoopBody* ptr = _alloc_ds(LoopBody);
    initAst(&ptr->ast, NULL, AST_LOOP_BODY);
    ptr->loop_body_statement_list = loop_body_statement_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1LoopBody(LoopBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = pass1LoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2LoopBody(LoopBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = pass2LoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3LoopBody(LoopBody* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = pass3LoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitLoopBody(LoopBody* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = emitLoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyLoopBody(LoopBody* ptr)
 *
 */
AstResult destroyLoopBody(LoopBody* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = destroyLoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpLoopBody(LoopBody* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->loop_body_statement_list != NULL) {
            AstResult res = dumpLoopBodyStatementList(ptr->loop_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
