/**
 * @file method_declaration.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _METHOD_DECLARATION_H_
#define _METHOD_DECLARATION_H_

#include "ast.h"

typedef enum {
    METHOD_DECLARATION_OK,
    METHOD_DECLARATION_ERROR,
} MethodDeclarationType;

struct _method_declaration_ {
    Ast ast;
    MethodDeclarationType type;
    TypeDefinition* type_definition;
    const char* symbol;
    FuncDeclParameterList* func_decl_parameter_list;
};

MethodDeclaration* createMethodDeclaration(TypeDefinition*, const char*, FuncDeclParameterList*);
AstResult pass1MethodDeclaration(MethodDeclaration*);
AstResult pass2MethodDeclaration(MethodDeclaration*);
AstResult pass3MethodDeclaration(MethodDeclaration*);
AstResult emitMethodDeclaration(MethodDeclaration*);
AstResult destroyMethodDeclaration(MethodDeclaration*);

#ifdef ENABLE_DUMP
AstResult dumpMethodDeclaration(MethodDeclaration* ptr);
#endif

#endif
