/**
 * @file method_declaration.c
 *
 * @brief $$ = createMethodDeclaration();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief MethodDeclaration* createMethodDeclaration(TypeDefinition* type_definition,
		const char* symbol,
		FuncDeclParameterList* func_decl_parameter_list)
 *
 */
MethodDeclaration* createMethodDeclaration(TypeDefinition* type_definition,
		const char* symbol,
		FuncDeclParameterList* func_decl_parameter_list) {

#ifdef ENABLE_TRACE
    printf("parser: createMethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    MethodDeclaration* ptr = _alloc_ds(MethodDeclaration);
    initAst(&ptr->ast, NULL, AST_METHOD_DECLARATION);
    ptr->type_definition = type_definition;
    ptr->symbol = symbol;
    ptr->func_decl_parameter_list = func_decl_parameter_list;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for MethodDeclaration data structure.
 *
 */
AstResult pass1MethodDeclaration(MethodDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1MethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass1TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = pass1FuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for MethodDeclaration data structure.
 *
 */
AstResult pass2MethodDeclaration(MethodDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2MethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass2TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = pass2FuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for MethodDeclaration data structure.
 *
 */
AstResult pass3MethodDeclaration(MethodDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3MethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass3TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = pass3FuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for MethodDeclaration data structure.
 *
 */
AstResult emitMethodDeclaration(MethodDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitMethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = emitTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = emitFuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a MethodDeclaration data structure.
 *
 */
AstResult destroyMethodDeclaration(MethodDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyMethodDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = destroyTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = destroyFuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump MethodDeclaration data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpMethodDeclaration(MethodDeclaration* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = dumpTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_decl_parameter_list != NULL) {
            AstResult res = dumpFuncDeclParameterList(ptr->func_decl_parameter_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
