/**
 * @file module_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _MODULE_LIST_H_
#define _MODULE_LIST_H_

#include "ast.h"

typedef enum {
    MODULE_LIST_OK,
    MODULE_LIST_ERROR,
} ModuleListType;

struct _module_list_ {
    Ast ast;
    ModuleListType type;
    ModuleItem* module_item;
    ModuleList* module_list;
};

ModuleList* createModuleList(ModuleItem*, ModuleList*);
AstResult pass1ModuleList(ModuleList*);
AstResult pass2ModuleList(ModuleList*);
AstResult pass3ModuleList(ModuleList*);
AstResult emitModuleList(ModuleList*);
AstResult destroyModuleList(ModuleList*);

#ifdef ENABLE_DUMP
AstResult dumpModuleList(ModuleList* ptr);
#endif

#endif
