/**
 * @file namespace_definition.c
 *
 * @brief $$ = createNamespaceDefinition();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief NamespaceDefinition* createNamespaceDefinition(const char* symbol,
		ModuleList* module_list)
 *
 */
NamespaceDefinition* createNamespaceDefinition(const char* symbol,
		ModuleList* module_list) {

#ifdef ENABLE_TRACE
    printf("parser: createNamespaceDefinition\\n");
#endif /* ENABLE_DUMP */

    NamespaceDefinition* ptr = _alloc_ds(NamespaceDefinition);
    initAst(&ptr->ast, NULL, AST_NAMESPACE_DEFINITION);
    ptr->symbol = symbol;
    ptr->module_list = module_list;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1NamespaceDefinition(NamespaceDefinition* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = pass1ModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2NamespaceDefinition(NamespaceDefinition* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = pass2ModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3NamespaceDefinition(NamespaceDefinition* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = pass3ModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitNamespaceDefinition(NamespaceDefinition* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = emitModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyNamespaceDefinition(NamespaceDefinition* ptr)
 *
 */
AstResult destroyNamespaceDefinition(NamespaceDefinition* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = destroyModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpNamespaceDefinition(NamespaceDefinition* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->module_list != NULL) {
            AstResult res = dumpModuleList(ptr->module_list);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
