/**
 * @file namespace_definition.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _NAMESPACE_DEFINITION_H_
#define _NAMESPACE_DEFINITION_H_

#include "ast.h"

typedef enum {
    NAMESPACE_DEFINITION_OK,
    NAMESPACE_DEFINITION_ERROR,
} NamespaceDefinitionType;

struct _namespace_definition_ {
    Ast ast;
    NamespaceDefinitionType type;
    const char* symbol;
    ModuleList* module_list;
};

NamespaceDefinition* createNamespaceDefinition(const char*, ModuleList*);
AstResult pass1NamespaceDefinition(NamespaceDefinition*);
AstResult pass2NamespaceDefinition(NamespaceDefinition*);
AstResult pass3NamespaceDefinition(NamespaceDefinition*);
AstResult emitNamespaceDefinition(NamespaceDefinition*);
AstResult destroyNamespaceDefinition(NamespaceDefinition*);

#ifdef ENABLE_DUMP
AstResult dumpNamespaceDefinition(NamespaceDefinition* ptr);
#endif

#endif
