/**
 * @file parameter_decl_element.c
 *
 * @brief $$ = createParameterDeclElement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief ParameterDeclElement* createParameterDeclElement(TypeDefinition* type_definition)
 *
 */
ParameterDeclElement* createParameterDeclElement(TypeDefinition* type_definition) {

#ifdef ENABLE_TRACE
    printf("parser: createParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    ParameterDeclElement* ptr = _alloc_ds(ParameterDeclElement);
    initAst(&ptr->ast, NULL, AST_PARAMETER_DECL_ELEMENT);
    ptr->type_definition = type_definition;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for ParameterDeclElement data structure.
 *
 */
AstResult pass1ParameterDeclElement(ParameterDeclElement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1ParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass1TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for ParameterDeclElement data structure.
 *
 */
AstResult pass2ParameterDeclElement(ParameterDeclElement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2ParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass2TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for ParameterDeclElement data structure.
 *
 */
AstResult pass3ParameterDeclElement(ParameterDeclElement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3ParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass3TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for ParameterDeclElement data structure.
 *
 */
AstResult emitParameterDeclElement(ParameterDeclElement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = emitTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a ParameterDeclElement data structure.
 *
 */
AstResult destroyParameterDeclElement(ParameterDeclElement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyParameterDeclElement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = destroyTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump ParameterDeclElement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpParameterDeclElement(ParameterDeclElement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = dumpTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
