/**
 * @file parameter_decl_element.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _PARAMETER_DECL_ELEMENT_H_
#define _PARAMETER_DECL_ELEMENT_H_

#include "ast.h"

typedef enum {
    PARAMETER_DECL_ELEMENT_OK,
    PARAMETER_DECL_ELEMENT_ERROR,
} ParameterDeclElementType;

struct _parameter_decl_element_ {
    Ast ast;
    ParameterDeclElementType type;
    TypeDefinition* type_definition;
};

ParameterDeclElement* createParameterDeclElement(TypeDefinition*);
AstResult pass1ParameterDeclElement(ParameterDeclElement*);
AstResult pass2ParameterDeclElement(ParameterDeclElement*);
AstResult pass3ParameterDeclElement(ParameterDeclElement*);
AstResult emitParameterDeclElement(ParameterDeclElement*);
AstResult destroyParameterDeclElement(ParameterDeclElement*);

#ifdef ENABLE_DUMP
AstResult dumpParameterDeclElement(ParameterDeclElement* ptr);
#endif

#endif
