/**
 * @file parameter_def_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _PARAMETER_DEF_LIST_H_
#define _PARAMETER_DEF_LIST_H_

#include "ast.h"

typedef enum {
    PARAMETER_DEF_LIST_OK,
    PARAMETER_DEF_LIST_ERROR,
} ParameterDefListType;

struct _parameter_def_list_ {
    Ast ast;
    ParameterDefListType type;
    SymbolDeclaration* symbol_declaration;
    ParameterDefList* parameter_def_list;
};

ParameterDefList* createParameterDefList(SymbolDeclaration*, ParameterDefList*);
AstResult pass1ParameterDefList(ParameterDefList*);
AstResult pass2ParameterDefList(ParameterDefList*);
AstResult pass3ParameterDefList(ParameterDefList*);
AstResult emitParameterDefList(ParameterDefList*);
AstResult destroyParameterDefList(ParameterDefList*);

#ifdef ENABLE_DUMP
AstResult dumpParameterDefList(ParameterDefList* ptr);
#endif

#endif
