/**
 * @file parameter_decl_list.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _PARAMETER_DECL_LIST_H_
#define _PARAMETER_DECL_LIST_H_

#include "ast.h"

typedef enum {
    PARAMETER_DECL_LIST_OK,
    PARAMETER_DECL_LIST_ERROR,
} ParameterDeclListType;

struct _parameter_decl_list_ {
    Ast ast;
    ParameterDeclListType type;
    ParameterDeclElement* parameter_decl_element;
    ParameterDeclList* parameter_decl_list;
};

ParameterDeclList* createParameterDeclList(ParameterDeclElement*, ParameterDeclList*);
AstResult pass1ParameterDeclList(ParameterDeclList*);
AstResult pass2ParameterDeclList(ParameterDeclList*);
AstResult pass3ParameterDeclList(ParameterDeclList*);
AstResult emitParameterDeclList(ParameterDeclList*);
AstResult destroyParameterDeclList(ParameterDeclList*);

#ifdef ENABLE_DUMP
AstResult dumpParameterDeclList(ParameterDeclList* ptr);
#endif

#endif
