/**
 * @file raise_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _RAISE_STATEMENT_H_
#define _RAISE_STATEMENT_H_

#include "ast.h"

typedef enum {
    RAISE_STATEMENT_OK,
    RAISE_STATEMENT_ERROR,
} RaiseStatementType;

struct _raise_statement_ {
    Ast ast;
    RaiseStatementType type;
    Expression* expression;
};

RaiseStatement* createRaiseStatement(Expression*);
AstResult pass1RaiseStatement(RaiseStatement*);
AstResult pass2RaiseStatement(RaiseStatement*);
AstResult pass3RaiseStatement(RaiseStatement*);
AstResult emitRaiseStatement(RaiseStatement*);
AstResult destroyRaiseStatement(RaiseStatement*);

#ifdef ENABLE_DUMP
AstResult dumpRaiseStatement(RaiseStatement* ptr);
#endif

#endif
