/**
 * @file raise_statement.c
 *
 * @brief $$ = createRaiseStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief RaiseStatement* createRaiseStatement(Expression* expression)
 *
 */
RaiseStatement* createRaiseStatement(Expression* expression) {

#ifdef ENABLE_TRACE
    printf("parser: createRaiseStatement\\n");
#endif /* ENABLE_DUMP */

    RaiseStatement* ptr = _alloc_ds(RaiseStatement);
    initAst(&ptr->ast, NULL, AST_RAISE_STATEMENT);
    ptr->expression = expression;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1RaiseStatement(RaiseStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass1Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2RaiseStatement(RaiseStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass2Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3RaiseStatement(RaiseStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass3Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitRaiseStatement(RaiseStatement* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = emitExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroyRaiseStatement(RaiseStatement* ptr)
 *
 */
AstResult destroyRaiseStatement(RaiseStatement* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = destroyExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpRaiseStatement(RaiseStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = dumpExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
