/**
 * @file return_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _RETURN_STATEMENT_H_
#define _RETURN_STATEMENT_H_

#include "ast.h"

typedef enum {
    RETURN_STATEMENT_OK,
    RETURN_STATEMENT_ERROR,
} ReturnStatementType;

struct _return_statement_ {
    Ast ast;
    ReturnStatementType type;
    ExpressionInParensRule* expression_in_parens_rule;
};

ReturnStatement* createReturnStatement(ExpressionInParensRule*);
AstResult pass1ReturnStatement(ReturnStatement*);
AstResult pass2ReturnStatement(ReturnStatement*);
AstResult pass3ReturnStatement(ReturnStatement*);
AstResult emitReturnStatement(ReturnStatement*);
AstResult destroyReturnStatement(ReturnStatement*);

#ifdef ENABLE_DUMP
AstResult dumpReturnStatement(ReturnStatement* ptr);
#endif

#endif
