/**
 * @file struct_body.c
 *
 * @brief $$ = createStructBody();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief StructBody* createStructBody(SymbolDeclaration* symbol_declaration,
		StructBody* struct_body)
 *
 */
StructBody* createStructBody(SymbolDeclaration* symbol_declaration,
		StructBody* struct_body) {

#ifdef ENABLE_TRACE
    printf("parser: createStructBody\\n");
#endif /* ENABLE_DUMP */

    StructBody* ptr = _alloc_ds(StructBody);
    initAst(&ptr->ast, NULL, AST_STRUCT_BODY);
    ptr->symbol_declaration = symbol_declaration;
    ptr->struct_body = struct_body;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for StructBody data structure.
 *
 */
AstResult pass1StructBody(StructBody* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1StructBody\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass1SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = pass1StructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for StructBody data structure.
 *
 */
AstResult pass2StructBody(StructBody* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2StructBody\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass2SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = pass2StructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for StructBody data structure.
 *
 */
AstResult pass3StructBody(StructBody* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3StructBody\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = pass3SymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = pass3StructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for StructBody data structure.
 *
 */
AstResult emitStructBody(StructBody* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitStructBody\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = emitSymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = emitStructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a StructBody data structure.
 *
 */
AstResult destroyStructBody(StructBody* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyStructBody\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = destroySymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = destroyStructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump StructBody data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpStructBody(StructBody* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->symbol_declaration != NULL) {
            AstResult res = dumpSymbolDeclaration(ptr->symbol_declaration);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->struct_body != NULL) {
            AstResult res = dumpStructBody(ptr->struct_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
