/**
 * @file struct_declaration.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _STRUCT_DECLARATION_H_
#define _STRUCT_DECLARATION_H_

#include "ast.h"

typedef enum {
    STRUCT_DECLARATION_OK,
    STRUCT_DECLARATION_ERROR,
} StructDeclarationType;

struct _struct_declaration_ {
    Ast ast;
    StructDeclarationType type;
    const char* symbol;
    StructBody* struct_body;
};

StructDeclaration* createStructDeclaration(const char*, StructBody*);
AstResult pass1StructDeclaration(StructDeclaration*);
AstResult pass2StructDeclaration(StructDeclaration*);
AstResult pass3StructDeclaration(StructDeclaration*);
AstResult emitStructDeclaration(StructDeclaration*);
AstResult destroyStructDeclaration(StructDeclaration*);

#ifdef ENABLE_DUMP
AstResult dumpStructDeclaration(StructDeclaration* ptr);
#endif

#endif
