/**
 * @file struct_body.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _STRUCT_BODY_H_
#define _STRUCT_BODY_H_

#include "ast.h"

typedef enum {
    STRUCT_BODY_OK,
    STRUCT_BODY_ERROR,
} StructBodyType;

struct _struct_body_ {
    Ast ast;
    StructBodyType type;
    SymbolDeclaration* symbol_declaration;
    StructBody* struct_body;
};

StructBody* createStructBody(SymbolDeclaration*, StructBody*);
AstResult pass1StructBody(StructBody*);
AstResult pass2StructBody(StructBody*);
AstResult pass3StructBody(StructBody*);
AstResult emitStructBody(StructBody*);
AstResult destroyStructBody(StructBody*);

#ifdef ENABLE_DUMP
AstResult dumpStructBody(StructBody* ptr);
#endif

#endif
