/**
 * @file switch_statement.c
 *
 * @brief $$ = createSwitchStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief SwitchStatement* createSwitchStatement(CompoundNameInParensRule* compound_name_in_parens_rule,
		CaseClauseList* case_clause_list)
 *
 */
SwitchStatement* createSwitchStatement(CompoundNameInParensRule* compound_name_in_parens_rule,
		CaseClauseList* case_clause_list) {

#ifdef ENABLE_TRACE
    printf("parser: createSwitchStatement\\n");
#endif /* ENABLE_DUMP */

    SwitchStatement* ptr = _alloc_ds(SwitchStatement);
    initAst(&ptr->ast, NULL, AST_SWITCH_STATEMENT);
    ptr->compound_name_in_parens_rule = compound_name_in_parens_rule;
    ptr->case_clause_list = case_clause_list;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for SwitchStatement data structure.
 *
 */
AstResult pass1SwitchStatement(SwitchStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1SwitchStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass1CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = pass1CaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for SwitchStatement data structure.
 *
 */
AstResult pass2SwitchStatement(SwitchStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2SwitchStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass2CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = pass2CaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for SwitchStatement data structure.
 *
 */
AstResult pass3SwitchStatement(SwitchStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3SwitchStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = pass3CompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = pass3CaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for SwitchStatement data structure.
 *
 */
AstResult emitSwitchStatement(SwitchStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitSwitchStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = emitCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = emitCaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a SwitchStatement data structure.
 *
 */
AstResult destroySwitchStatement(SwitchStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroySwitchStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = destroyCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = destroyCaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump SwitchStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpSwitchStatement(SwitchStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->compound_name_in_parens_rule != NULL) {
            AstResult res = dumpCompoundNameInParensRule(ptr->compound_name_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->case_clause_list != NULL) {
            AstResult res = dumpCaseClauseList(ptr->case_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
