/**
 * @file symbol_declaration.c
 *
 * @brief $$ = createSymbolDeclaration();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief SymbolDeclaration* createSymbolDeclaration(SymbolType* symbol_type)
 *
 */
SymbolDeclaration* createSymbolDeclaration(SymbolType* symbol_type) {

#ifdef ENABLE_TRACE
    printf("parser: createSymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    SymbolDeclaration* ptr = _alloc_ds(SymbolDeclaration);
    initAst(&ptr->ast, NULL, AST_SYMBOL_DECLARATION);
    ptr->symbol_type = symbol_type;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for SymbolDeclaration data structure.
 *
 */
AstResult pass1SymbolDeclaration(SymbolDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1SymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = pass1SymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for SymbolDeclaration data structure.
 *
 */
AstResult pass2SymbolDeclaration(SymbolDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2SymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = pass2SymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for SymbolDeclaration data structure.
 *
 */
AstResult pass3SymbolDeclaration(SymbolDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3SymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = pass3SymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for SymbolDeclaration data structure.
 *
 */
AstResult emitSymbolDeclaration(SymbolDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitSymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = emitSymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a SymbolDeclaration data structure.
 *
 */
AstResult destroySymbolDeclaration(SymbolDeclaration* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroySymbolDeclaration\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = destroySymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump SymbolDeclaration data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpSymbolDeclaration(SymbolDeclaration* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->symbol_type != NULL) {
            AstResult res = dumpSymbolType(ptr->symbol_type);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
