/**
 * @file symbol_type.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _SYMBOL_TYPE_H_
#define _SYMBOL_TYPE_H_

#include "ast.h"

typedef enum {
    SYMBOL_TYPE_OK,
    SYMBOL_TYPE_ERROR,
} SymbolTypeType;

struct _symbol_type_ {
    Ast ast;
    SymbolTypeType type;
    TypeDefinition* type_definition;
    const char* symbol;
};

SymbolType* createSymbolType(TypeDefinition*, const char*);
AstResult pass1SymbolType(SymbolType*);
AstResult pass2SymbolType(SymbolType*);
AstResult pass3SymbolType(SymbolType*);
AstResult emitSymbolType(SymbolType*);
AstResult destroySymbolType(SymbolType*);

#ifdef ENABLE_DUMP
AstResult dumpSymbolType(SymbolType* ptr);
#endif

#endif
