/**
 * @file symbol_type.c
 *
 * @brief $$ = createSymbolType();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief SymbolType* createSymbolType(TypeDefinition* type_definition,
		const char* symbol)
 *
 */
SymbolType* createSymbolType(TypeDefinition* type_definition,
		const char* symbol) {

#ifdef ENABLE_TRACE
    printf("parser: createSymbolType\\n");
#endif /* ENABLE_DUMP */

    SymbolType* ptr = _alloc_ds(SymbolType);
    initAst(&ptr->ast, NULL, AST_SYMBOL_TYPE);
    ptr->type_definition = type_definition;
    ptr->symbol = symbol;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1SymbolType(SymbolType* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass1TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2SymbolType(SymbolType* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass2TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3SymbolType(SymbolType* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = pass3TypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitSymbolType(SymbolType* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = emitTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}

/**
 * @brief void destroySymbolType(SymbolType* ptr)
 *
 */
AstResult destroySymbolType(SymbolType* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = destroyTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpSymbolType(SymbolType* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->type_definition != NULL) {
            AstResult res = dumpTypeDefinition(ptr->type_definition);
            if(res != AST_RES_OK)
                return res;
        }

    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
