/**
 * @file symbol_declaration.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _SYMBOL_DECLARATION_H_
#define _SYMBOL_DECLARATION_H_

#include "ast.h"

typedef enum {
    SYMBOL_DECLARATION_OK,
    SYMBOL_DECLARATION_ERROR,
} SymbolDeclarationType;

struct _symbol_declaration_ {
    Ast ast;
    SymbolDeclarationType type;
    SymbolType* symbol_type;
};

SymbolDeclaration* createSymbolDeclaration(SymbolType*);
AstResult pass1SymbolDeclaration(SymbolDeclaration*);
AstResult pass2SymbolDeclaration(SymbolDeclaration*);
AstResult pass3SymbolDeclaration(SymbolDeclaration*);
AstResult emitSymbolDeclaration(SymbolDeclaration*);
AstResult destroySymbolDeclaration(SymbolDeclaration*);

#ifdef ENABLE_DUMP
AstResult dumpSymbolDeclaration(SymbolDeclaration* ptr);
#endif

#endif
