/**
 * @file trace_statement.c
 *
 * @brief $$ = createTraceStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief TraceStatement* createTraceStatement(const char* strg)
 *
 */
TraceStatement* createTraceStatement(const char* strg) {

#ifdef ENABLE_TRACE
    printf("parser: createTraceStatement\\n");
#endif /* ENABLE_DUMP */

    TraceStatement* ptr = _alloc_ds(TraceStatement);
    initAst(&ptr->ast, NULL, AST_TRACE_STATEMENT);
    ptr->strg = strg;

    return ptr;
}

/**
 * @brief Execute pass 1 analysis for this data structure.
 *
 */
AstResult pass1TraceStatement(TraceStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items// nothing to traverse
    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for this data structure.
 *
 */
AstResult pass2TraceStatement(TraceStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items// nothing to traverse
    }
    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for this data structure.
 *
 */
AstResult pass3TraceStatement(TraceStatement* ptr) {

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items// nothing to traverse
    }
    return AST_RES_OK;
}

/**
 * @brief Emit final output for this data structure.
 *
 */
AstResult emitTraceStatement(TraceStatement* ptr) {

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items// nothing to traverse
    }
    return AST_RES_OK;
}

/**
 * @brief void destroyTraceStatement(TraceStatement* ptr)
 *
 */
AstResult destroyTraceStatement(TraceStatement* ptr) {

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items// nothing to traverse
        _free(ptr);
    }
    return AST_RES_OK;
}

/**
 * @brief Dump the data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpTraceStatement(TraceStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items// nothing to traverse
    }
    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
