/**
 * @file try_statement.c
 *
 * @brief $$ = createTryStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief TryStatement* createTryStatement(FuncBodyStatementList* func_body_statement_list,
		ExceptClauseList* except_clause_list)
 *
 */
TryStatement* createTryStatement(FuncBodyStatementList* func_body_statement_list,
		ExceptClauseList* except_clause_list) {

#ifdef ENABLE_TRACE
    printf("parser: createTryStatement\\n");
#endif /* ENABLE_DUMP */

    TryStatement* ptr = _alloc_ds(TryStatement);
    initAst(&ptr->ast, NULL, AST_TRY_STATEMENT);
    ptr->func_body_statement_list = func_body_statement_list;
    ptr->except_clause_list = except_clause_list;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for TryStatement data structure.
 *
 */
AstResult pass1TryStatement(TryStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1TryStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass1FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = pass1ExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for TryStatement data structure.
 *
 */
AstResult pass2TryStatement(TryStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2TryStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass2FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = pass2ExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for TryStatement data structure.
 *
 */
AstResult pass3TryStatement(TryStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3TryStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = pass3FuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = pass3ExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for TryStatement data structure.
 *
 */
AstResult emitTryStatement(TryStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitTryStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = emitFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = emitExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a TryStatement data structure.
 *
 */
AstResult destroyTryStatement(TryStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyTryStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = destroyFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = destroyExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump TryStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpTryStatement(TryStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->func_body_statement_list != NULL) {
            AstResult res = dumpFuncBodyStatementList(ptr->func_body_statement_list);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->except_clause_list != NULL) {
            AstResult res = dumpExceptClauseList(ptr->except_clause_list);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
