/**
 * @file try_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _TRY_STATEMENT_H_
#define _TRY_STATEMENT_H_

#include "ast.h"

typedef enum {
    TRY_STATEMENT_OK,
    TRY_STATEMENT_ERROR,
} TryStatementType;

struct _try_statement_ {
    Ast ast;
    TryStatementType type;
    FuncBodyStatementList* func_body_statement_list;
    ExceptClauseList* except_clause_list;
};

TryStatement* createTryStatement(FuncBodyStatementList*, ExceptClauseList*);
AstResult pass1TryStatement(TryStatement*);
AstResult pass2TryStatement(TryStatement*);
AstResult pass3TryStatement(TryStatement*);
AstResult emitTryStatement(TryStatement*);
AstResult destroyTryStatement(TryStatement*);

#ifdef ENABLE_DUMP
AstResult dumpTryStatement(TryStatement* ptr);
#endif

#endif
