/**
 * @file type_statement.c
 *
 * @brief $$ = createTypeStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief TypeStatement* createTypeStatement(Expression* expression)
 *
 */
TypeStatement* createTypeStatement(Expression* expression) {

#ifdef ENABLE_TRACE
    printf("parser: createTypeStatement\\n");
#endif /* ENABLE_DUMP */

    TypeStatement* ptr = _alloc_ds(TypeStatement);
    initAst(&ptr->ast, NULL, AST_TYPE_STATEMENT);
    ptr->expression = expression;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for TypeStatement data structure.
 *
 */
AstResult pass1TypeStatement(TypeStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1TypeStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass1Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for TypeStatement data structure.
 *
 */
AstResult pass2TypeStatement(TypeStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2TypeStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass2Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for TypeStatement data structure.
 *
 */
AstResult pass3TypeStatement(TypeStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3TypeStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = pass3Expression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for TypeStatement data structure.
 *
 */
AstResult emitTypeStatement(TypeStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitTypeStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = emitExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a TypeStatement data structure.
 *
 */
AstResult destroyTypeStatement(TypeStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyTypeStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = destroyExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump TypeStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpTypeStatement(TypeStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression != NULL) {
            AstResult res = dumpExpression(ptr->expression);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
