/**
 * @file type_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _TYPE_STATEMENT_H_
#define _TYPE_STATEMENT_H_

#include "ast.h"

typedef enum {
    TYPE_STATEMENT_OK,
    TYPE_STATEMENT_ERROR,
} TypeStatementType;

struct _type_statement_ {
    Ast ast;
    TypeStatementType type;
    Expression* expression;
};

TypeStatement* createTypeStatement(Expression*);
AstResult pass1TypeStatement(TypeStatement*);
AstResult pass2TypeStatement(TypeStatement*);
AstResult pass3TypeStatement(TypeStatement*);
AstResult emitTypeStatement(TypeStatement*);
AstResult destroyTypeStatement(TypeStatement*);

#ifdef ENABLE_DUMP
AstResult dumpTypeStatement(TypeStatement* ptr);
#endif

#endif
