/**
 * @file while_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _WHILE_STATEMENT_H_
#define _WHILE_STATEMENT_H_

#include "ast.h"

typedef enum {
    WHILE_STATEMENT_OK,
    WHILE_STATEMENT_ERROR,
} WhileStatementType;

struct _while_statement_ {
    Ast ast;
    WhileStatementType type;
    ExpressionInParensRule* expression_in_parens_rule;
    FuncBody* func_body;
};

WhileStatement* createWhileStatement(ExpressionInParensRule*, FuncBody*);
AstResult pass1WhileStatement(WhileStatement*);
AstResult pass2WhileStatement(WhileStatement*);
AstResult pass3WhileStatement(WhileStatement*);
AstResult emitWhileStatement(WhileStatement*);
AstResult destroyWhileStatement(WhileStatement*);

#ifdef ENABLE_DUMP
AstResult dumpWhileStatement(WhileStatement* ptr);
#endif

#endif
