/**
 * @file while_statement.c
 *
 * @brief $$ = createWhileStatement();
 *
 * NOTE: This file is automatically generated by the boilerplate script.
 */
#include "memory.h"
#include "ast.h"

/**
 * @brief WhileStatement* createWhileStatement(ExpressionInParensRule* expression_in_parens_rule,
		FuncBody* func_body)
 *
 */
WhileStatement* createWhileStatement(ExpressionInParensRule* expression_in_parens_rule,
		FuncBody* func_body) {

#ifdef ENABLE_TRACE
    printf("parser: createWhileStatement\\n");
#endif /* ENABLE_DUMP */

    WhileStatement* ptr = _alloc_ds(WhileStatement);
    initAst(&ptr->ast, NULL, AST_WHILE_STATEMENT);
    ptr->expression_in_parens_rule = expression_in_parens_rule;
    ptr->func_body = func_body;


    return ptr;
}

/**
 * @brief Execute pass 1 analysis for WhileStatement data structure.
 *
 */
AstResult pass1WhileStatement(WhileStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass1WhileStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 1 routines

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass1ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass1FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 2 analysis for WhileStatement data structure.
 *
 */
AstResult pass2WhileStatement(WhileStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass2WhileStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 2 routines

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass2ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass2FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Execute pass 3 analysis for WhileStatement data structure.
 *
 */
AstResult pass3WhileStatement(WhileStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: pass3WhileStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the pass 3 routines

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = pass3ExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = pass3FuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Emit final output for WhileStatement data structure.
 *
 */
AstResult emitWhileStatement(WhileStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: emitWhileStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // perform the emitter routines

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = emitExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = emitFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}

/**
 * @brief Destroy a WhileStatement data structure.
 *
 */
AstResult destroyWhileStatement(WhileStatement* ptr) {

#ifdef ENABLE_TRACE
    printf("parser: destroyWhileStatement\\n");
#endif /* ENABLE_DUMP */

    if(ptr != NULL) {
        // destroy these data elements

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = destroyExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = destroyFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

        _free(ptr);
    }

    return AST_RES_OK;
}

/**
 * @brief Dump WhileStatement data type and progress the tree.
 *
 */
#ifdef ENABLE_DUMP
AstResult dumpWhileStatement(WhileStatement* ptr) {

    //(void)ptr;
    if(ptr != NULL) {
        dumpAst(&ptr->ast);
        // dump this item

        // traverse the data structure items
        if(ptr->expression_in_parens_rule != NULL) {
            AstResult res = dumpExpressionInParensRule(ptr->expression_in_parens_rule);
            if(res != AST_RES_OK)
                return res;
        }

        if(ptr->func_body != NULL) {
            AstResult res = dumpFuncBody(ptr->func_body);
            if(res != AST_RES_OK)
                return res;
        }

    }

    return AST_RES_OK;
}
#endif /* ENABLE_DUMP */
