/**
 * @file yield_statement.h
 *
 * NOTE: This file is generated by the boilerplate functionality.
 */
#ifndef _YIELD_STATEMENT_H_
#define _YIELD_STATEMENT_H_

#include "ast.h"

typedef enum {
    YIELD_STATEMENT_OK,
    YIELD_STATEMENT_ERROR,
} YieldStatementType;

struct _yield_statement_ {
    Ast ast;
    YieldStatementType type;
};

YieldStatement* createYieldStatement();
AstResult pass1YieldStatement(YieldStatement*);
AstResult pass2YieldStatement(YieldStatement*);
AstResult pass3YieldStatement(YieldStatement*);
AstResult emitYieldStatement(YieldStatement*);
AstResult destroyYieldStatement(YieldStatement*);

#ifdef ENABLE_DUMP
AstResult dumpYieldStatement(YieldStatement* ptr);
#endif

#endif
